[package]
name = "geoconv"
version = "0.4.2"
edition = "2021"
license = "MIT"
authors = ["Paul Tagliamonte <paultag@gmail.com>"]
repository = "https://github.com/paultag/geoconv-rs"
description = "convert between different coordinate systems"

[dependencies]
